### ISSUE TITLE
ModuleNotFoundError: No module named 'raven'      ---------           when i exceuted "python manage.py makemigrations"  occured this error， but i had installed package 'raven' ....

### ISSUE THREAD

**Issue by simpelbill** [mtianyan/VueDjangoAntdProBookShop#20]
Traceback (most recent call last):
  File "C:\python36\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\python36\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "C:\python36\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\python36\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\python36\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\python36\lib\site-packages\django\core\checks\urls.py", line 35, in check_url_namespaces_unique
    if not getattr(settings, 'ROOT_URLCONF', None):
  File "C:\python36\lib\site-packages\django\conf\__init__.py", line 79, in __getattr__
    self._setup(name)
  File "C:\python36\lib\site-packages\django\conf\__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\python36\lib\site-packages\django\conf\__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\code\python\VueDjangoFrameWorkShop\VueDjangoFrameWorkShop\settings.py", line 228, in <module>
    import raven
ModuleNotFoundError: No module named 'raven'

**Comment by mtianyan** [comment]
已移除raven 依赖
